import "@/styles/globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import QueryProvider from "@/provider/QueryProvider";
import { AuthentificationProvider } from "@/provider/AuthentificationProvider";
import NextAuthSessionProvider from "@/provider/sessionProvider";
const outfit = Outfit({ subsets: ["latin"], weight: ["300", "500"] });

export const metadata: Metadata = {
  title: "Entertainment App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <QueryProvider>
          <NextAuthSessionProvider>
            <AuthentificationProvider>{children}</AuthentificationProvider>
          </NextAuthSessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
